# Generated by Django 4.1 on 2022-08-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cumulative_score', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Level1',
        ),
        migrations.DeleteModel(
            name='Level2',
        ),
        migrations.DeleteModel(
            name='Level3',
        ),
        migrations.DeleteModel(
            name='Level4',
        ),
        migrations.DeleteModel(
            name='Level5',
        ),
    ]
